project:
  type: book
  output-dir: _book

book:
  title: "sample book"
  author: "me"
  date: today
  date-format: long
  reader-mode: true

  page-footer:
    left: |
      sample book
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  cover-image: cover.png
  favicon: cover.png
  
  chapters:
    - index.qmd
    - one.qmd
    - two.qmd
    - three.qmd
    - four.qmd
    - five.qmd
    - six.qmd
    - seven.qmd
    - eight.qmd
    - nine.qmd
    - ten.qmd
    - eleven.qmd

format:
  pdf:
    pdf-engine: latexmk
    pdf-engine-opt: -xelatex
    documentclass: krantz
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \usepackage[titles]{tocloft}
        \cftsetindents{figure}{0em}{3.5em}
        \cftsetindents{table}{0em}{3.5em}
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
        showspaces = false,
        showtabs = false,
        breaksymbolleft={},
        breaklines
        % Note: setting commandchars=\\\{\} here will cause an error 
        }
    include-after-body: 
      text: |
        \printindex
    lof: true
    lot: true
    prefer-html: true
    toc: true
    number-sections: true
    colorlinks: true
    toc-depth: 5
    keep-md: false
    keep-tex: false
crossref:
  chapters: true
  lof-title: "List of Figures"
  lot-title: "List of Tables"